"""init_db

Revision ID: ed7d79196572
Revises: 
Create Date: 2024-07-14 12:00:32.321325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7d79196572'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id', 'id'),
    sa.UniqueConstraint('pk_id')
    )
    op.create_table('centrio_treinamento',
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=60), nullable=False),
    sa.Column('proprietario', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id', 'id'),
    sa.UniqueConstraint('pk_id')
    )
    op.create_table('atleta',
    sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('idade', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('centro_treinamentoid', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.pk_id'], ),
    sa.ForeignKeyConstraint(['centro_treinamentoid'], ['centrio_treinamento.pk_id'], ),
    sa.PrimaryKeyConstraint('pk_id', 'id'),
    sa.UniqueConstraint('categoria_id'),
    sa.UniqueConstraint('centro_treinamentoid'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('pk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atleta')
    op.drop_table('centrio_treinamento')
    op.drop_table('categoria')
    # ### end Alembic commands ###
